[package]
name = "wado"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.6.6", package = "gtk4" }
time = "0.3.20"
uuid = { version = "1.3.2", features = ["v4"] }
